// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BeautifierMinifierCommon: typeof import('./../src/components/BeautifierMinifierCommon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElectronVersions: typeof import('./../src/components/ElectronVersions.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    MenuItems: typeof import('./../src/components/MenuItems.vue')['default']
    NavigationBar: typeof import('./../src/components/NavigationBar.vue')['default']
    PageContainer: typeof import('./../src/components/PageContainer.vue')['default']
    ReactiveCounter: typeof import('./../src/components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./../src/components/ReactiveHash.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemConfig: typeof import('./../src/components/SystemConfig.vue')['default']
    TitleBar: typeof import('./../src/components/TitleBar.vue')['default']
  }
}

export {}
