// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BeautifierMinifierCommon: typeof import('./../src/components/BeautifierMinifierCommon.vue')['default']
    ClipPanel: typeof import('./../src/components/tools/ClipPanel.vue')['default']
    DiffView: typeof import('./../src/components/DiffView.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElectronVersions: typeof import('./../src/components/ElectronVersions.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ICodiconChromeClose: typeof import('~icons/codicon/chrome-close')['default']
    ICodiconChromeMaximize: typeof import('~icons/codicon/chrome-maximize')['default']
    ICodiconChromeMinimize: typeof import('~icons/codicon/chrome-minimize')['default']
    ICodiconChromeRestore: typeof import('~icons/codicon/chrome-restore')['default']
    LanguageToggle: typeof import('./../src/components/LanguageToggle.vue')['default']
    MenuItems: typeof import('./../src/components/MenuItems.vue')['default']
    PageContainer: typeof import('./../src/components/PageContainer.vue')['default']
    ReactiveCounter: typeof import('./../src/components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./../src/components/ReactiveHash.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemConfig: typeof import('./../src/components/SystemConfig.vue')['default']
    TitleBar: typeof import('./../src/components/TitleBar.vue')['default']
  }
}

export {}
